# Generated by Django 5.2.8 on 2025-11-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogger',
            options={'ordering': ['-first_joined']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='blogger',
            name='first_joined',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='bio',
            field=models.CharField(help_text='Write a little about yourself', max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('blog_text', models.TextField(help_text='Blog post here')),
                ('title', models.CharField(help_text='Enter a title', max_length=40)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogger')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.post'),
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
