# Generated by Django 5.2.8 on 2025-11-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogger_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='bio',
            field=models.TextField(help_text='Write a little about yourself', max_length=300, null=True),
        ),
    ]
