# Generated by Django 5.2.8 on 2025-11-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogger_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='last_name',
        ),
    ]
